### ISSUE TITLE
save_path is not mas compatible

### ISSUE THREAD

**Issue by GymRat102** [astrosander/cambridge-dictionary-audio#1]
Hi,

Thanks for this really helpful utility.

But right now it seems doesn't handle file path on macOS correctly. It uses backslash as save path so it will not correctly save file on current folder as intended:

![image](https://github.com/astrosander/cambridge-dictionary-audio/assets/35257543/9e92b3bd-2e41-4968-b97c-2a72f0e7af07)

Simply change this line:
https://github.com/astrosander/cambridge-dictionary-audio/blob/8e273c711621bcd7f36cb3eb2445863f388ee73e/main.py#L58

to

`save_path = f"{folder_path}/{word}.mp3"`

will make it work. But it sure can be more smarter than that e.g. detect what os it's running on and set save_path as os-specific.

Just raise this issue here and I am happy to do a PR if we agree on a good way to fix.

**Comment by astrosander** [comment]
Fixed a bag: https://github.com/astrosander/cambridge-dictionary-audio/commit/6d917aa45af0c0c424d6fb465bc2c5067fba5f07
